---
title: "abalone"
output: html_document
---

---
title: "TidyTuesday Caret and Tidymodels"
output: github_document
---

Video: https://www.youtube.com/watch?v=hAMjhbPJTkA&list=PLJfshcspBCYeJeO8YFT5e5HxuYOb5a_1W&index=45

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidymodels)
df <- read_csv("abalone.data", col_names = FALSE)
colnames(df) <- c("Sex", "Length", "Diameter", "Height", "Whole_Weight","Shucked_Weight", "Viscera_Weight", "Shell_Weight", "Rings")
df$Sex <- as.factor(df$Sex)
set.seed(80)
df <- sample_n(df, size = 800)

```

```{r}
#Splitting train and test sets the tidy way
tidy_split <- initial_split(df, prop = .8)
tidy_train <- training(tidy_split)
tidy_test <- testing(tidy_split)
```


```{r}
#Tidy way of preprocessing
tidy_rec <- recipe(Rings~., data = tidy_train) %>% 
  step_center(all_predictors(), -all_nominal()) %>% 
  step_scale(all_predictors(), -all_nominal()) %>% 
  step_dummy(all_nominal(), one_hot = TRUE)
tidy_prep <- prep(tidy_rec)
tidy_juice <- juice(tidy_prep)
```


```{r}
#set sampling procedures using k-folds
tidy_kfolds <- vfold_cv(tidy_train, v = 10, strata = "Rings")
```


```{r}
#Tuning models

##Tidy way 
#Specify model
tidy_rf <- rand_forest(
  mtry = tune(),
  trees = 1000,
  min_n = tune()
  ) %>% 
  set_mode("regression") %>% 
  set_engine("randomForest")

#Specify modeling procdeure
tidy_wf <- workflow() %>% 
  add_recipe(tidy_rec) %>% 
  add_model(tidy_rf)

#Tune the model
tidy_tune <- tune_grid(
  tidy_wf,
  resamples = tidy_kfolds,
  grid = 5
)
```


```{r}
#Evaluate the models 
#Evaulate the tidy model
tidy_best_tune <- tidy_tune %>% select_best("rmse")
```

```{r}
#Finalize our models
tidy_final_model <- finalize_model(tidy_rf, tidy_best_tune)
tidy_final_workflow <- workflow() %>% 
  add_recipe(tidy_rec) %>% 
  add_model(tidy_final_model)
tidy_final_workflow
```



```{r}
#Evaluate the test sets using the final models
#Tidy way 
tidy_final_workflow %>% last_fit(tidy_split) %>% collect_metrics()
```

