---
title: "Video Game Popularity Over Time"
output: html_document
runtime: shiny
---
```{r setup, include = FALSE, warning = FALSE, error = FALSE, message = FALSE, echo = FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
 

```{r, include = FALSE}
library(shiny)
library(plotly)
library(dplyr)
library(ggplot2)
library(scales)
library(lubridate)
library(readr)
library(tidytuesdayR)
library(forcats)
theme_set(theme_light())
tt = tidytuesdayR::tt_load('2021-03-16')
head(data)

#create date column that is a date field with lubridate
games = tt$games%>%
  mutate(avg_peak_perc = parse_number(avg_peak_perc)) %>%  
           mutate(date = ymd(paste(year, month, 1))) %>% 
           filter(date > min(date)) %>% 
           mutate(month = fct_reorder(month, month(date))) %>%  #reorder as months occur throughout the year
  mutate(gamename = fct_reorder(gamename, -avg))

game_names = levels(games$gamename)  #bring most popular games to top

```


```{r, warning=FALSE, error = FALSE}
inputPanel(
  selectizeInput("games", label = "Games:",
                 choices = game_names,
                 selected = head(game_names,9),
                 multiple = TRUE),
  
      dateRangeInput('dateRange',
      label = 'Date range input: yyyy-mm-dd',
      start = Sys.Date() - 2, end = Sys.Date() + 2
    ),
)

renderPlotly({
  req({input$games})
  g <- games %>% 
    filter(gamename %in% input$games) %>%
    filter(date >=)
    ggplot(aes(x = date, y = avg))+
    geom_line()+
    expand_limits(y = 0)+
    scale_y_continuous(label = comma)+
    facet_wrap(~gamename, scales = 'free_y')+
    labs(x = 'Date',y = 'Average Number of Players per Month')
  
  ggplotly(g)
})
```

   


