```{r}
library(tidyverse)
tournament <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-10-06/tournament.csv")

head(tournament)
```


```{r}
#what expected number of wins based on what seed you are
tournament %>% 
  group_by(seed) %>% 
  summarise(exp_wins = mean(tourney_w, na.rm = T)) %>% 
  ggplot(aes(seed, exp_wins))+
  geom_point(size = 3)
```

```{r}
#binned
tournament %>%
  ggplot(aes(seed, tourney_w)) +
  geom_bin2d(binwidth = c(1, 1), alpha = 0.8) +
  scale_fill_gradient(low = "gray85", high = "midnightblue") +
  labs(fill = "number of\nteams", y = "tournament wins")
```

```{r}
#splines
library(splines2)

plot_smoother <- function(deg_free) {
  p <- ggplot(tournament, aes(seed, tourney_w)) +
    geom_bin2d(binwidth = c(1, 1), alpha = 0.8) +
    scale_fill_gradient(low = "gray85", high = "midnightblue") +
    geom_smooth(
      method = lm, se = FALSE, color = "black",
      formula = y ~ ns(x, df = deg_free)
    ) +
    labs(
      fill = "number of\nteams", y = "tournament wins",
      title = paste(deg_free, "spline terms")
    )

  print(p)
}

walk(c(2, 4, 6, 8, 10, 15), plot_smoother)
```

```{r}
#model
library(tidymodels)

set.seed(123)
tourney_split <- tournament %>% 
  filter(!is.na(seed)) %>% 
  initial_split(strata = seed)

tourney_train <- training(tourney_split)
tourney_test <- testing(tourney_split)

tourney_folds <-  bootstraps(tourney_train)

```

```{r}
#recipe
tourney_rec <- recipe(tourney_w~seed, data = tourney_train) %>% 
  step_ns(seed, deg_free = tune("seed_splines")) #step make new splines
  
```

```{r}
#model
lm_spec <- linear_reg() %>% 
  set_engine("lm")

#workflow
tourney_wflow <- workflow() %>% 
  add_model(lm_spec) %>% 
  add_recipe(tourney_rec)
```

```{r}
#tune df hyperparameter
doParallel::registerDoParallel()

save_preds <- control_grid(save_pred = T)

#create your tibble of different dfs
spline_grid <- tibble(seed_splines = c(1:3, 5, 7, 10))
spline_grid

spline_res <- tune_grid(
  tourney_wflow,
  resamples = tourney_folds,
  grid = spline_grid,
  control = save_preds
)

```

```{r}
#evaluate 
collect_metrics(spline_res) %>%
  ggplot(aes(seed_splines, mean, color = .metric)) +
  geom_line(size = 1.5, alpha = 0.5) +
  geom_point(size = 3) +
  facet_wrap(~.metric, ncol = 1, scales = "free_y") +
  labs(x = "degrees of freedom", y = NULL) +
  theme(legend.position = "none")


#We could choose either by percent loss in performance or within one standard error in performance.
select_by_pct_loss(spline_res, metric = "rmse", limit = 5, seed_splines)
select_by_one_std_err(spline_res, metric = "rmse", seed_splines)

```

```{r}
#finalize the workflow 
final_wflow <- finalize_workflow(tourney_wflow, tibble(seed_splines = 3))
tourney_fit <- fit(final_wflow, tourney_train)
tourney_fit
```

```{r}
#predict with test data 
tourney_test %>%
  bind_cols(predict(tourney_fit, tourney_test)) %>%
  metrics(tourney_w, .pred)

predict(tourney_fit, new_data = tibble(seed = 1:16))
```








