```{r}
astronauts <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-07-14/astronauts.csv")

astronauts %>%
  count(in_orbit, sort = TRUE)

skimr::skim(astronauts)
```

```{r}
#histogram of mission hours
astronauts %>% 
  ggplot(aes(hours_mission))+
  geom_histogram()+
  scale_x_log10()
```

```{r}
#decades using floor math
astronauts %>%
  mutate(year_of_mission = 10* year_of_mission %/% 10,
         year_of_mission = factor(year_of_mission)) %>% 
  ggplot(aes(year_of_mission, hours_mission, fill = year_of_mission))+
  geom_boxplot()+
  scale_y_log10()
```

```{r}
astronauts_df <- astronauts %>% 
  select(name, mission_title, hours_mission, military_civilian, occupation, 
         year_of_mission, in_orbit) %>% 
  mutate(in_orbit = case_when(str_detect(in_orbit, "^Salyut")~ "Salyut",
                              str_detect(in_orbit,"STS") ~ "STS",
                                         TRUE ~ in_orbit)) %>% 
  filter(hours_mission > 0) %>% 
  mutate(hours_mission = log(hours_mission),
         occupation = str_to_lower(occupation)) %>% 
  na.omit()
```


```{r}
#model with bagging
set.seed(211)
astronauts_split <- initial_split(astronauts_df, strata = hours_mission)
astronauts_train <- training(astronauts_split)
astronauts_test <- testing(astronauts_split)

```

```{r}
astronauts_rec <- recipe(hours_mission ~ ., data = astronauts_train) %>%
  update_role(name, mission_title, new_role = "id") %>%
  step_other(occupation, in_orbit,
    threshold = 0.005, other = "Other"
  ) %>%
  step_dummy(all_nominal(), -has_role("id"))
```


```{r}
#2 different ways of bootstrapping 
library(baguette)
tree_spec <- bag_tree() %>% 
  set_engine("rpart", times = 25) %>% 
  set_mode("regression")

mars_spec <- bag_mars() %>% 
  set_engine("earth", times = 25) %>% 
  set_mode("regression")

```

```{r}
astronauts_wflow <- workflow() %>% 
  add_recipe(astronauts_rec) 

#add each type of bagging spec to the workflow
tree_res <- astronauts_wflow %>% 
  add_model(tree_spec) %>% 
  fit(astronauts_train)
tree_res

mars_res <- astronauts_wflow %>%
  add_model(mars_spec) %>%
  fit(astronauts_train)
mars_res

#can see VIP for each 
```

```{r}
#evaluate
test_res <- astronauts_test %>% 
  bind_cols(predict(tree_res, astronauts_test)) %>% 
  rename(.pred_tree = .pred) %>% 
    bind_cols(predict(mars_res, astronauts_test)) %>% 
  rename(.pred_mars = .pred)

#check metrics
test_res %>% 
  metrics(hours_mission,.pred_tree)

test_res %>% 
  metrics(hours_mission,.pred_mars)
```

```{r}
#create synthetic data to test model
new_astronauts <- crossing(
  in_orbit = fct_inorder(c("ISS", "STS", "Mir", "Other")),
  military_civilian = "civilian",
  occupation = "Other",
  year_of_mission = seq(1960, 2020, by = 10),
  name = "id", mission_title = "id"
) %>%
  filter(
    !(in_orbit == "ISS" & year_of_mission < 2000),
    !(in_orbit == "Mir" & year_of_mission < 1990),
    !(in_orbit == "STS" & year_of_mission > 2010),
    !(in_orbit == "STS" & year_of_mission < 1980)
  )

new_astronauts
```

```{r}
#tree model first
new_astronauts %>%
  bind_cols(predict(tree_res, new_astronauts)) %>%
  ggplot(aes(year_of_mission, .pred, color = in_orbit)) +
  geom_line(size = 1.5, alpha = 0.7) +
  geom_point(size = 2) +
  labs(
    x = NULL, y = "Duration of mission in hours (predicted, on log scale)",
    color = NULL, title = "How did the duration of astronauts' missions change over time?",
    subtitle = "Predicted using bagged decision tree model"
  )
```

```{r}
#then mars model

new_astronauts %>%
  bind_cols(predict(mars_res, new_astronauts)) %>%
  ggplot(aes(year_of_mission, .pred, color = in_orbit)) +
  geom_line(size = 1.5, alpha = 0.7) +
  geom_point(size = 2) +
  labs(
    x = NULL, y = "Duration of mission in hours (predicted, on log scale)",
    color = NULL, title = "How did the duration of astronauts' missions change over time?",
    subtitle = "Predicted using bagged decision tree model"
  )
```










